<?php
/**
 * IndividualAccountTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\EbayIdentityClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Identity API
 *
 * Retrieves the authenticated user's account profile information. It can be used to let users log into your app or site using eBay, which frees you from needing to store and protect user's PII (Personal Identifiable Information) data.
 *
 * OpenAPI spec version: v1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\EbayIdentityClient;

/**
 * IndividualAccountTest Class Doc Comment
 *
 * @category    Class
 * @description The type that defines the fields for the information of an individual account.
 * @package     Swagger\EbayIdentityClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class IndividualAccountTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "IndividualAccount"
     */
    public function testIndividualAccount()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {
    }

    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {
    }

    /**
     * Test attribute "primary_phone"
     */
    public function testPropertyPrimaryPhone()
    {
    }

    /**
     * Test attribute "registration_address"
     */
    public function testPropertyRegistrationAddress()
    {
    }

    /**
     * Test attribute "secondary_phone"
     */
    public function testPropertySecondaryPhone()
    {
    }
}
